---

- hosts: all
  become: true
  tasks:
  - name: Install Debian Packages
    apt:
      name:
        - nginx
        - dehydrated
      state: present

  - name: 'Create /srv/www/empty'
    file:
      path: /srv/www/empty
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: 'Create /srv/www/smethurst'
    file:
      path: /srv/www/smethurst
      state: directory
      owner: fantasticlife
      group: fantasticlife
      mode: 0755

  - name: 'Download dhparam file from Mozilla'
    get_url:
      url: https://ssl-config.mozilla.org/ffdhe2048.txt
      dest: /etc/nginx/dhparam.txt
      mode: '0644'

  - name: 'Copy over modern SSL nginx settings'
    copy:
      src: modern-ssl.inc
      dest: /etc/nginx/conf.d/modern-ssl.inc
      mode: '0644'
    notify:
    - 'Restart Nginx'

  - name: 'Copy accross Nginx configuration file'
    copy:
      src: nginx.conf
      dest: /etc/nginx/sites-available/smethurst
    notify:
    - 'Restart Nginx'

  - name: 'Enable Nginx configuration file'
    file:
      src: /etc/nginx/sites-available/smethurst
      dest: /etc/nginx/sites-enabled/smethurst
      state: link
    notify:
    - 'Restart Nginx'

  - name: "Ensure that dehydrated's domains.txt exists"
    file:
      path: /etc/dehydrated/domains.txt
      state: file
      owner: root
      group: root
      mode: 0644

  - name: "Add domains to dehydrated's domains.txt"
    lineinfile:
      path: /etc/dehydrated/domains.txt
      line: "smethur.st www.smethur.st"
      regexp: 'smethur\.st'
    notify:
      - 'Run dehydrated'

  handlers:
  - name: 'Restart Nginx'
    become: true
    service: name=nginx state=restarted
  - name: 'Run dehydrated'
    command: dehydrated -c
